# JukeANator PlayList — Wed Jun 10 12:10:40 EDT 2026
/mnt/readyNAS/Rock_On_Third/Soundtracks/Top Gun/Cheap Trick-02-Mighty Wings.mp3
/mnt/readyNAS/Rock_On_Third/Soundtracks/Top Gun/Kenny Loggins-03-Playing With The Boys.mp3
/mnt/readyNAS/Rock_On_Third/Soundtracks/Top Gun/Teena Marie-04-Lead Me On.mp3
/mnt/readyNAS/Rock_On_Third/Soundtracks/Top Gun/Berlin-05-Take My Breath Away.mp3
/mnt/readyNAS/Rock_On_Third/Soundtracks/Top Gun/Miami Sound Machine-06-Hot Summer Nights.mp3
/mnt/readyNAS/Rock_On_Third/Soundtracks/Top Gun/Loverboy-07-Heaven In Your Eyes.mp3
/mnt/readyNAS/Rock_On_Third/Soundtracks/Top Gun/Larry Greene-08-Through The Fire.mp3
/mnt/readyNAS/Rock_On_Third/Soundtracks/Top Gun/Marietta-09-Destination Unknown.mp3
/mnt/readyNAS/Rock_On_Third/Soundtracks/Top Gun/Harold Faltermeyer-10-Top Gun Anthem (with Steve Stevens).mp3
